/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'service' : IDL.Text,
  'name' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const Contact = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const Feedback = IDL.Record({
  'id' : IDL.Nat,
  'service' : IDL.Text,
  'name' : IDL.Text,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'bookAppointment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'getBooking' : IDL.Func([IDL.Nat], [Booking], ['query']),
  'getContact' : IDL.Func([IDL.Nat], [Contact], ['query']),
  'getFeedbackById' : IDL.Func([IDL.Nat], [IDL.Opt(Feedback)], ['query']),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'submitFeedback' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'service' : IDL.Text,
    'name' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Contact = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Feedback = IDL.Record({
    'id' : IDL.Nat,
    'service' : IDL.Text,
    'name' : IDL.Text,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'bookAppointment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getBooking' : IDL.Func([IDL.Nat], [Booking], ['query']),
    'getContact' : IDL.Func([IDL.Nat], [Contact], ['query']),
    'getFeedbackById' : IDL.Func([IDL.Nat], [IDL.Opt(Feedback)], ['query']),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitFeedback' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };