/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'service' : string,
  'name' : string,
  'message' : string,
  'phone' : string,
}
export interface Contact {
  'id' : bigint,
  'name' : string,
  'message' : string,
  'phone' : string,
}
export interface Feedback {
  'id' : bigint,
  'service' : string,
  'name' : string,
  'comment' : string,
  'rating' : bigint,
}
export interface _SERVICE {
  'bookAppointment' : ActorMethod<[string, string, string, string], bigint>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllContacts' : ActorMethod<[], Array<Contact>>,
  'getAllFeedback' : ActorMethod<[], Array<Feedback>>,
  'getBooking' : ActorMethod<[bigint], Booking>,
  'getContact' : ActorMethod<[bigint], Contact>,
  'getFeedbackById' : ActorMethod<[bigint], [] | [Feedback]>,
  'submitContactForm' : ActorMethod<[string, string, string], bigint>,
  'submitFeedback' : ActorMethod<[string, string, bigint, string], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];